version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: fastapi-store-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C.UTF-8
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: fastapi-store-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      SECRET_KEY_ACCESS: ${SECRET_KEY_ACCESS}
      SECRET_KEY_REFRESH: ${SECRET_KEY_REFRESH}
      JWT_SIGNING_ALGORITHM: ${JWT_SIGNING_ALGORITHM}
      PYTHONPATH: /usr/src/app:/usr/src/app/src
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

volumes:
  pgdata: