"""Add cascade delete on cart_items.cart_id foreign key

Revision ID: 631e77bf2ea9
Revises: de3b8dba50b0
Create Date: 2025-05-21 18:57:49.453121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "631e77bf2ea9"
down_revision: Union[str, None] = "de3b8dba50b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
